#TODO: incomplete, fill it later

activity_name: "coffee"
name_experiment: "breakfast_iter"
name_trial: "experiment_k_"

segment:
    background_used: 0


embedding:
    no_cache: 0
    type_text_label: "word2vec" #number_canonical, word2vec, number_shuffle
    label_decimal: 1
    validation_percentage: 0
    #TODO: look at line 49 original matlab code: driversetparams_breakfast()...
    train:
        actFunc: 'rectMax' #TODO generalise by implementing setup_activation_fn and get_param
        batch_size: 300
        max_epochs: 1
        label_vec_dim: 200 
        latent_space_dim: 50
        frame_features_dim: 64
        gmargin: 100 #DOUBT: not present in bf_iter_coffee declarations, whre is this declared in matlab code. is this config file the right place to declare it?
        thrglobalscore: 0 #TODO: belonged to dataset, atm hard-coded change
        smoothnum: 0 #TODO: belonged to dataset, atm hard-coded change
        reg_const_gamma: 2e-10 #TODO: belonged to dataset, atm hard-coded change
        lr: 1e-7
        momentum: 0.9
        dataset: " " #TODO why is it instructions in original code?
        
        featureE:
            neg_response: 0
            word_count_DCM: 1
features:


gmm:
  infOut:
    rho_prior: 1