#TODO: incomplete, fill it later

activity_name: "coffee"
name_experiment: "breakfast_iter"
name_trial: "experiment_k_"

segment:
    background_used: 0


embedding:
    no_cache: 0
    type_text_label: "word2vec" #number_canonical, word2vec, number_shuffle
    label_decimal: 1
    validation_percentage: 0
    #TODO: look at line 49 original matlab code: driversetparams_breakfast()...
    train:
        max_epochs: 
        word_dim: 
        semantic_space: 50
        img_dim:
        gmargin: #DOUBT: not present in bf_iter_coffee declarations, whre is this declared in matlab code. is this config file the right place to declare it?
        dataset: " " #TODO why is it instructions in original code?
        featureE:
            neg_response: 0
            word_count_DCM: 1
features:


gmm:
  infOut:
    rho_prior: 1